# Generated by Django 5.1.7 on 2025-03-08 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SMSMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=20)),
                ('receiver', models.CharField(max_length=20)),
                ('body', models.TextField()),
                ('timestamp', models.DateTimeField()),
                ('message_type', models.CharField(max_length=10)),
                ('delivery', models.CharField(blank=True, max_length=20, null=True)),
                ('read', models.BooleanField(default=False)),
            ],
        ),
    ]
